name: Release Binary using Zig (Testing)

on:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    name: Release - ${{ matrix.platform.readable-target-name }}
    strategy:
      matrix:
        platform:
          - readable-target-name: Linux x86_64
            runs-on: ubuntu-latest
            archive-name: gilt-linux-x86_64
            rustup-target: x86_64-unknown-linux-gnu
            zigbuild-target: x86_64-unknown-linux-gnu.2.17
            build-dst-dir: x86_64-unknown-linux-gnu

          - readable-target-name: Linux ARM
            runs-on: ubuntu-latest
            archive-name: gilt-linux-aarch64
            rustup-target: aarch64-unknown-linux-gnu
            zigbuild-target: aarch64-unknown-linux-gnu.2.17
            build-dst-dir: aarch64-unknown-linux-gnu

          - readable-target-name: macOS Universal Binary
            runs-on: macOS-latest
            archive-name: gilt-macos-ub
            rustup-target: x86_64-apple-darwin aarch64-apple-darwin
            zigbuild-target: universal2-apple-darwin
            build-dst-dir: universal2-apple-darwin


    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal
    
      - name: Install Cross-Compilation Target
        run: rustup target add ${{ matrix.platform.rustup-target }}

      - if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        name: Enable Rust Cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          key: ${{ matrix.platform.zigbuild-target }}
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo-sbom and cargo-zigbuild
        uses: taiki-e/install-action@735e5933943122c5ac182670a935f54a949265c1 # v2.52.4
        with:
          tool: cargo-sbom, cargo-zigbuild

      - if: ${{ startsWith(matrix.platform.runs-on, 'ubuntu-') }}
        name: Install Zig (Linux)
        run: sudo snap install zig --beta --classic
    
      - if: ${{ startsWith(matrix.platform.runs-on, 'macOS-') }}
        name: Install old Zig (macOS) (https://github.com/rust-cross/cargo-zigbuild/issues/324)
        run: |
          wget "https://github.com/Homebrew/homebrew-core/raw/c54c3a4ec99029097088d72533dd1b2f75a7ac3c/Formula/z/zig.rb"
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=TRUE brew install --formula zig.rb

      - if: ${{ startsWith(matrix.platform.runs-on, 'macOS-') }}
        name: Set macOS SDK Environment Variable
        run: |
          sudo xcode-select -s /Library/Developer/CommandLineTools
          echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> "${GITHUB_ENV}"

      - name: Zigbuild
        run: cargo zigbuild --locked --release --target ${{ matrix.platform.zigbuild-target }}

      - name: Produce SBOM
        run: cargo sbom --output-format=spdx_json_2_3 > sbom-spdx.json

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@48ce35fb40c3dab00791a3d6c485022341354c44 # v0.0.6
        with:
          executable-name: gilt
          target: ${{ matrix.platform.build-dst-dir }}
          changes-file:
          extra-files: |
            README.md
            sbom-spdx.json
          archive-name: ${{ matrix.platform.archive-name }}
      
#      - if: ${{ ! startsWith(matrix.platform.runs-on, 'windows-') && startsWith(github.ref, 'refs/tags/') }}
#        name: Publish SBOM Attestation (non-Windows)
#        uses: actions/attest-sbom@115c3be05ff3974bcbd596578934b3f9ce39bf68 # v2.2.0
#        with:
#          subject-path: ./${{ matrix.platform.archive-name }}.tar.gz, ./target/release/gilt, ./sbom-spdx.json
#          sbom-path: ./sbom-spdx.json
#
#      - if: ${{ ! startsWith(matrix.platform.runs-on, 'windows-') && startsWith(github.ref, 'refs/tags/') }}
#        name: Publish Artifact Attestation (non-Windows)
#        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
#        with:
#          subject-path: ./${{ matrix.platform.archive-name }}.tar.gz, ./target/release/gilt, ./sbom-spdx.json
#
#      - if: ${{ startsWith(matrix.platform.runs-on, 'windows-') && startsWith(github.ref, 'refs/tags/') }}
#        name: Publish SBOM Attestation (Windows)
#        uses: actions/attest-sbom@115c3be05ff3974bcbd596578934b3f9ce39bf68 # v2.2.0
#        with:
#          subject-path: .\${{ matrix.platform.archive-name }}.zip, .\target\release\gilt.exe, .\sbom-spdx.json
#          sbom-path: .\sbom-spdx.json
#
#      - if: ${{ startsWith(matrix.platform.runs-on, 'windows-') && startsWith(github.ref, 'refs/tags/') }}
#        name: Publish Artifact Attestation (Windows)
#        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
#        with:
#          subject-path: .\${{ matrix.platform.archive-name }}.zip, .\target\release\gilt.exe, .\sbom-spdx.json
